---
title: "Code book"
output: html_document
---

#Code book
##Getting and cleaning data: week 4 assignment

###Variables

The following describes the variables contained within the tidy data set


* "subject" : a number corresponding to the subject identity 
* "activity_type" : a factor describing the type of activity conducted during the experiment. The factor has six levels; WALKING, WALKING_UPSTAIRS, WALKING_DOWNSTAIRS, SITTING, STANDING, LAYING.  

The rest of the variables correspond to different measurements averaged over each subject and each activity. The following list describes how to read the coded information contained within each variable name:

* avg_: reflects that the values in the tidy data set are averaged over multiple signal data, grouped by activity and subject. 
* t: the measurement is in the time domain
* f: the measurement is in the frequency domain, via application of a fast fourier transform
* Body: the measurement is for a body acceleration signal
* Gravity: the measurement is for a gravity acceleration signal
* Acc: the measurement comes from the accelerometer
* Gyro: the measurement comes from the gyroscope
* Jerk: the measurement is for a Jerk signal
* mean(): the measurement is the mean of the signal data
* std(): the measurement is the standard deviation of the signal data
* Mag: the measurement is the euclidian norm magnitude of the signal data
* X: the measurement is the signal data in the X direction
* Y: the measurement is the signal data in the Y direction
* Z: the measurement is the signal data in the Z direction

Applying the above, "**avg_tBodyAccJerk-mean()-X**", for example, becomes: "average body linear acceleration time domain jerk signal mean in X, from the accelerometer"

The full list of measurement variables is as follows: 

 "avg_tBodyAcc-mean()-X"          
  "avg_tBodyAcc-mean()-Y"  
  "avg_tBodyAcc-mean()-Z"        
  "avg_tBodyAcc-std()-X"           
  "avg_tBodyAcc-std()-Y"     
  "avg_tBodyAcc-std()-Z"      
  "avg_tGravityAcc-mean()-X"       
 "avg_tGravityAcc-mean()-Y"   
 "avg_tGravityAcc-mean()-Z"   
 "avg_tGravityAcc-std()-X"        
 "avg_tGravityAcc-std()-Y"    
 "avg_tGravityAcc-std()-Z"     
 "avg_tBodyAccJerk-mean()-X"      
 "avg_tBodyAccJerk-mean()-Y" 
 "avg_tBodyAccJerk-mean()-Z"   
 "avg_tBodyAccJerk-std()-X"       
 "avg_tBodyAccJerk-std()-Y"    
 "avg_tBodyAccJerk-std()-Z"    
 "avg_tBodyGyro-mean()-X"         
 "avg_tBodyGyro-mean()-Y"      
 "avg_tBodyGyro-mean()-Z"      
 "avg_tBodyGyro-std()-X"          
 "avg_tBodyGyro-std()-Y"        
 "avg_tBodyGyro-std()-Z"        
 "avg_tBodyGyroJerk-mean()-X"     
 "avg_tBodyGyroJerk-mean()-Y"    
 "avg_tBodyGyroJerk-mean()-Z"   
 "avg_tBodyGyroJerk-std()-X"      
 "avg_tBodyGyroJerk-std()-Y"    
 "avg_tBodyGyroJerk-std()-Z"    
 "avg_tBodyAccMag-mean()"         
 "avg_tBodyAccMag-std()"         
 "avg_tGravityAccMag-mean()"     
 "avg_tGravityAccMag-std()"       
 "avg_tBodyAccJerkMag-mean()"     
 "avg_tBodyAccJerkMag-std()"     
 "avg_tBodyGyroMag-mean()"        
 "avg_tBodyGyroMag-std()"        
 "avg_tBodyGyroJerkMag-mean()"   
 "avg_tBodyGyroJerkMag-std()"     
 "avg_fBodyAcc-mean()-X"          
 "avg_fBodyAcc-mean()-Y"          
 "avg_fBodyAcc-mean()-Z"          
 "avg_fBodyAcc-std()-X"           
 "avg_fBodyAcc-std()-Y"           
 "avg_fBodyAcc-std()-Z"           
 "avg_fBodyAccJerk-mean()-X"      
 "avg_fBodyAccJerk-mean()-Y"     
 "avg_fBodyAccJerk-mean()-Z"      
 "avg_fBodyAccJerk-std()-X"       
 "avg_fBodyAccJerk-std()-Y"      
 "avg_fBodyAccJerk-std()-Z"       
 "avg_fBodyGyro-mean()-X"         
 "avg_fBodyGyro-mean()-Y"         
 "avg_fBodyGyro-mean()-Z"         
 "avg_fBodyGyro-std()-X"          
 "avg_fBodyGyro-std()-Y"         
 "avg_fBodyGyro-std()-Z"          
 "avg_fBodyAccMag-mean()"         
 "avg_fBodyAccMag-std()"           
 "avg_fBodyBodyAccJerkMag-mean()" 
 "avg_fBodyBodyAccJerkMag-std()"   
 "avg_fBodyBodyGyroMag-mean()"     
 "avg_fBodyBodyGyroMag-std()"     
 "avg_fBodyBodyGyroJerkMag-mean()"
 "avg_fBodyBodyGyroJerkMag-std()" 


